name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
      
    - name: Initialize Kafka and Zookeeper
      run: cd ../../ && pwd && make kafka-start

    - name: Test
      run: cd ./src/memory && go test
    
    - name: Stop Kafka and Zookeeper
      run: cd ../../ && make kafka-stop
  
